services:
    postgres:
        build:
            context: .
            dockerfile: postgres.Dockerfile
        container_name: memeDB_postgres
        command:
            [
                "postgres",
                "-c",
                "logging_collector=on",
                "-c",
                "log_destination=jsonlog",
            ]
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: memedb
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    meme-service:
        build:
            context: .
            dockerfile: meme-service.Dockerfile
        container_name: memeDB_meme-service
        environment:
            - SERVER_PORT=50051
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=memedb
        ports:
            - 50051:50051
        depends_on:
            - postgres
        volumes:
            - ./images:/app/images
    gateway:
        build:
            context: .
            dockerfile: gateway.Dockerfile
        container_name: memeDB_gateway
        environment:
            - GRPC_HOST=meme-service
            - GRPC_PORT=50051
        ports:
            - 8080:8080
        depends_on:
            - meme-service
        volumes:
            - ./images:/app/images:ro

volumes:
    postgres_data:
