global:
    scrape_interval: 30s

scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]
    - job_name: "memes-gateway"
      static_configs:
          - targets: ["host.docker.internal:8080"]
